### ISSUE TITLE
Rendezés gombokon miért nem nyíl van

### ISSUE THREAD

**Issue by eknagy** [muezli/AFT20200330#1]
A rendezés gombokon miért nem nyíl van?
Úgy lenne jó, hogy A=>Z

**Comment by HertelD-GDF** [comment]
Rendezés gombokon lévő felirat javítás lett
[Commit #a83a92e](https://github.com/muezli/AFT20200330/commit/a83a92e9b909f04573e952f2bd6e913c2e8c4c93)
